version: "3.8"
services:
  partner-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./Partner App/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
